# Generated by Django 5.0.4 on 2024-04-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aya_number", models.IntegerField()),
                ("arabic_text", models.TextField()),
                ("english_translation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Qari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qari_name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("englishName", models.CharField(max_length=128)),
                ("englishNameTranslation", models.CharField(max_length=128)),
                ("numberofAyahs", models.IntegerField()),
                ("revelationType", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Recitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="audio/")),
                (
                    "aya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vbv_app.aya"
                    ),
                ),
                (
                    "qari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vbv_app.qari"
                    ),
                ),
                (
                    "sura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vbv_app.sura"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aya",
            name="sura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vbv_app.sura"
            ),
        ),
    ]
