# Generated by Django 5.0.4 on 2024-04-16 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbv_app', '0002_remove_aya_id_alter_aya_sura'),
    ]

    operations = [
        migrations.AddField(
            model_name='aya',
            name='verse_key',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aya',
            name='sura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbv_app.sura'),
        ),
    ]
