# Generated by Django 5.0.4 on 2024-04-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbv_app', '0003_aya_verse_key_alter_aya_sura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aya',
            name='verse_key',
            field=models.CharField(default=0, max_length=128, primary_key=True, serialize=False),
        ),
    ]
