# Generated by Django 5.0.4 on 2024-04-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbv_app', '0005_remove_recitation_aya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recitation',
            name='qari',
        ),
        migrations.RemoveField(
            model_name='recitation',
            name='sura',
        ),
    ]
