# Generated by Django 5.0.4 on 2024-04-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbv_app', '0006_remove_recitation_qari_remove_recitation_sura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recitation',
        ),
    ]
